# -*- coding: utf-8 -*-
"""estatistica2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kSv_J7YcbhfUvQgc9TK7o4joPkmx_VFT
"""

import pandas as pd
import numpy as np

s2=pd.Series([1,2,-5,0],index=['joao1','b','c','d'])

s2

s2.index

s2['joao1']=1000
s2

#comparacao
s2[s2>0]

#algebra
s2*2

#verificar se vazio
s2.isnull()

#nao ta vazio
s2.notnull()

import pandas as pd
import numpy as np

dados={'estado':['SP','MG','PR','SP','MG','PR'],
       'ano':[2019,2019,2019,2020,2020,2020],
       'pop':[45.9,21.2,16.7,46.7,21.4,17.3]}

df1=pd.DataFrame(dados)

#cabeçalho
df1.head(2)

#corpo
df1.tail(2)

#exemplo de forma aleatoria
df1.sample(3)

#criar um dataframe encima de outro dataframe
df2=pd.DataFrame(dados,columns=['ano','estado','pop'])

df2.ano

df2.dtypes

df2['estimativa']=50
df2

df2['estimativa']=np.arange(6)
df2

df3=df2[['ano']]
df3

#pesquisa como remover o bloco
df2.drop('estimativa', axis=1, inplace=True)
df2

df2['estimativa']=40
df2

df2.shape

df2.iloc[:,:]

df2.shape[0]
df2

#pesquisar em casa
df2['tudo']=dados
df2.iloc[0,1]
df2

df2.columns=['Ano','Estado','População']
df2

df2.describe(include='all')

del df2['tudo']

df2['Ano']+2

df2.drop([0,1])

df2.iloc[0]



df2.describe(include="all")

alterar valores cuidado
df2["ano"]+2

#dropar sem deletar para avaliar
df2.drop([0,1])

df2.iloc[0]