# -*- coding: utf-8 -*-
"""entrega final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WQ8KYMJcaZ1ZwAp5PUx1EAY1rN7HLPE_
"""

#agora é a prova dos 9

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df1 = pd.read_csv('./cet.csv')
display(df1.head(5))

df1.columns=['Empresa','Mes','Ano','Cargo','Salario']
display(df1.head(5))

df1.describe()

salario_ano=pd.Series.sum(df1['Salario'])
print(f'Salario Total Anual: R${salario_ano:.2f}')

media_mes=pd.Series.mean(df1['Salario'])
print(f'Media de salario Mensal: R${media_mes:.2f}')

df1.value_counts(['Cargo'])

df1.plot()

plt.plot(df1.iloc[:, 1], df1.iloc[:, 3], marker='o')

plt.xlabel('Mês')
plt.ylabel('Salarios')
plt.title('Salarios Pagos no Mes')
plt.grid(True)
plt.show()



